--with
--    f as (select * from bronze_fragebogen),
--    meta as (select id, system_created_at from bronze_fragebogen)
--    select
--        f.id submission_id,
--        f.system_created_at submission_timestamp,
--        f.payload -> 'data' ->> 'besucherkennung' besucherkennung,
--        f.payload -> 'data' ->> 'plz3' plz3,
--
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'counsel', false) test_beratung,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hiv_lab', false) test_hiv_lab,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hiv_poc', false) test_hiv_poc,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'tp', false) test_tp_lab,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_throat', false) test_gon_chl_rac,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_urine', false) test_gon_chl_uri,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_vag', false) test_gon_chl_vag,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_anal', false) test_gon_chl_rek,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hav', false) test_hav,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'anti-hbc', false) test_hbv,
--        COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hcv', false) test_hcv,
--
--        f.payload -> 'data' ->> 'beraterkennung'  beraterkennung,
--        f.payload -> 'data' ->> 'beraterkommentar' beraterkommentar,
--
--        f.payload -> 'data' ->> 'gender' gender,
--        f.payload -> 'data' ->> 'gender_other' gender_other,
--        f.payload -> 'data' ->> 'orientation' orientation,
--        f.payload -> 'data' ->> 'orientation_other' orientation_other,
--        f.payload -> 'data' ->> 'birth_country' birth_country,
--        f.payload -> 'data' ->> 'insurance' insurance,
--        f.payload -> 'data' ->> 'doctor' doctor,
--        f.payload -> 'data' ->> 'hiv_test' hiv_test,
--
--        f.payload -> 'data' ->> 'risk_type' risk_type,
--        f.payload -> 'data' ->> 'risk_type_other' risk_type_other,
--        f.payload -> 'data' ->> 'prep_use' prep_use,
--        f.payload -> 'data' ->> 'hiv_risk_selfest' hiv_risk_selfest,
--        f.payload -> 'data' ->> 'hiv_test_prev'  hiv_test_prev,
--        f.payload -> 'data' ->> 'hiv_test_prev_count' hiv_test_prev_count,
--         f.payload -> 'data' ->> 'hiv_test_prev_year' hiv_test_prev_year,
--        f.payload -> 'data' ->> 'hiv_test_prev_confirm' hiv_test_prev_confirm,
--        f.payload -> 'data' ->> 'sexual_risk_time' sexual_risk_time,
--        f.payload -> 'data' -> 'risk_situation' risk_situation,
--        f.payload -> 'data' ->> 'risk_situation_other' risk_situation_other,
--        f.payload -> 'data' ->> 'risk_country' risk_country,
--
--        f.payload -> 'data' ->> 'risk_gv' risk_gv,
--        f.payload -> 'data' ->> 'risk_condom' risk_condom,
--        f.payload -> 'data' ->> 'risk_oral' risk_oral,
--        f.payload -> 'data' -> 'risk_reasons' risk_reasons,
--        f.payload -> 'data' ->> 'risk_reasons_other' risk_reasons_other,
--        f.payload -> 'data' ->> 'risk_drugs' risk_drugs,
--
--        f.payload -> 'data' ->> 'sti_history_yesno' sti_history_yesno,
--        f.payload -> 'data' -> 'sti_history_which' sti_history_which,
--        f.payload -> 'data' ->> 'sti_history_which_other' sti_history_which_other,
--        f.payload -> 'data' -> 'sti_history_years' sti_history_years,
--        f.payload -> 'data' ->> 'hep_a_history' hep_a_history,
--        f.payload -> 'data' ->> 'hep_b_history' hep_b_history,
--
--        'bronze_fragebogen' system_source ,
--        now() system_created_at,
--        f.payload -> 'meta'  ->> 'feVersion' system_fe_version,
--        f.payload -> 'meta'  ->> 'schemaVersion'  system_schema_version
--    from f;



INSERT INTO silver_fragebogen (
    submission_id,
    submission_timestamp,
    besucherkennung,
    plz3,
    test_beratung,
    test_hiv_lab,
    test_hiv_poc,
    test_tp_lab,
    test_gon_chl_rac,
    test_gon_chl_uri,
    test_gon_chl_vag,
    test_gon_chl_rek,
    test_hav,
    test_hbv,
    test_hcv,
    beraterkennung,
    beraterkommentar,
    gender,
    gender_other,
    orientation,
    orientation_other,
    birth_country,
    insurance,
    doctor,
    hiv_test,
    risk_type,
    risk_type_other,
    prep_use,
    hiv_risk_selfest,
    hiv_test_prev,
    hiv_test_prev_count,
    hiv_test_prev_year,
    hiv_test_prev_confirm,
    sexual_risk_time,
    risk_situation,
    risk_situation_other,
    risk_country,
    risk_gv,
    risk_condom,
    risk_oral,
    risk_reasons,
    risk_reasons_other,
    risk_drugs,
    sti_history_yesno,
    sti_history_which,
    sti_history_which_other,
    sti_history_years,
    hep_a_history,
    hep_b_history,
    system_source,
    system_created_at,
    system_fe_version,
    system_schema_version
)
WITH f AS (
    SELECT *
    FROM bronze_fragebogen
)
SELECT
    f.id AS submission_id,
    f.system_created_at AS submission_timestamp,
    f.payload -> 'data' ->> 'besucherkennung' AS besucherkennung,
    f.payload -> 'data' ->> 'plz3' AS plz3,

    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'counsel', false) AS test_beratung,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hiv_lab', false) AS test_hiv_lab,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hiv_poc', false) AS test_hiv_poc,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'tp', false) AS test_tp_lab,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_throat', false) AS test_gon_chl_rac,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_urine', false) AS test_gon_chl_uri,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_vag', false) AS test_gon_chl_vag,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'go_ct_anal', false) AS test_gon_chl_rek,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hav', false) AS test_hav,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'anti-hbc', false) AS test_hbv,
    COALESCE(f.payload -> 'data' -> 'testanforderungen' ? 'hcv', false) AS test_hcv,

    f.payload -> 'data' ->> 'beraterkennung' AS beraterkennung,
    f.payload -> 'data' ->> 'beraterkommentar' AS beraterkommentar,

    f.payload -> 'data' ->> 'gender' AS gender,
    f.payload -> 'data' ->> 'gender_other' AS gender_other,
    f.payload -> 'data' ->> 'orientation' AS orientation,
    f.payload -> 'data' ->> 'orientation_other' AS orientation_other,
    f.payload -> 'data' ->> 'birth_country' AS birth_country,
    f.payload -> 'data' ->> 'insurance' AS insurance,
    f.payload -> 'data' ->> 'doctor' AS doctor,
    f.payload -> 'data' ->> 'hiv_test' AS hiv_test,

    f.payload -> 'data' -> 'risk_type' AS risk_type,
    f.payload -> 'data' ->> 'risk_type_other' AS risk_type_other,
    f.payload -> 'data' ->> 'prep_use' AS prep_use,
    f.payload -> 'data' ->> 'hiv_risk_selfest' AS hiv_risk_selfest,
    f.payload -> 'data' ->> 'hiv_test_prev' AS hiv_test_prev,
    f.payload -> 'data' ->> 'hiv_test_prev_count' AS hiv_test_prev_count,
    f.payload -> 'data' ->> 'hiv_test_prev_year' AS hiv_test_prev_year,
    f.payload -> 'data' ->> 'hiv_test_prev_confirm' AS hiv_test_prev_confirm,
    f.payload -> 'data' -> 'sexual_risk_time' AS sexual_risk_time,
    f.payload -> 'data' -> 'risk_situation' AS risk_situation,
    f.payload -> 'data' ->> 'risk_situation_other' AS risk_situation_other,
    f.payload -> 'data' ->> 'risk_country' AS risk_country,

    f.payload -> 'data' ->> 'risk_gv' AS risk_gv,
    f.payload -> 'data' ->> 'risk_condom' AS risk_condom,
    f.payload -> 'data' ->> 'risk_oral' AS risk_oral,
    f.payload -> 'data' -> 'risk_reasons' AS risk_reasons,
    f.payload -> 'data' ->> 'risk_reasons_other' AS risk_reasons_other,
    f.payload -> 'data' ->> 'risk_drugs' AS risk_drugs,

    f.payload -> 'data' ->> 'sti_history_yesno' AS sti_history_yesno,
    f.payload -> 'data' -> 'sti_history_which' AS sti_history_which,
    f.payload -> 'data' ->> 'sti_history_which_other' AS sti_history_which_other,
    f.payload -> 'data' -> 'sti_history_years' AS sti_history_years,
    f.payload -> 'data' ->> 'hep_a_history' AS hep_a_history,
    f.payload -> 'data' ->> 'hep_b_history' AS hep_b_history,

    'bronze_fragebogen' AS system_source,
    now() AS system_created_at,
    f.payload -> 'meta' ->> 'feVersion' AS system_fe_version,
    f.payload -> 'meta' ->> 'schemaVersion' AS system_schema_version
FROM f
ON CONFLICT (submission_id)
DO UPDATE SET
    submission_timestamp   = EXCLUDED.submission_timestamp,
    besucherkennung        = EXCLUDED.besucherkennung,
    plz3                   = EXCLUDED.plz3,
    test_beratung          = EXCLUDED.test_beratung,
    test_hiv_lab           = EXCLUDED.test_hiv_lab,
    test_hiv_poc           = EXCLUDED.test_hiv_poc,
    test_tp_lab            = EXCLUDED.test_tp_lab,
    test_gon_chl_rac       = EXCLUDED.test_gon_chl_rac,
    test_gon_chl_uri       = EXCLUDED.test_gon_chl_uri,
    test_gon_chl_vag       = EXCLUDED.test_gon_chl_vag,
    test_gon_chl_rek       = EXCLUDED.test_gon_chl_rek,
    test_hav               = EXCLUDED.test_hav,
    test_hbv               = EXCLUDED.test_hbv,
    test_hcv               = EXCLUDED.test_hcv,
    beraterkennung         = EXCLUDED.beraterkennung,
    beraterkommentar       = EXCLUDED.beraterkommentar,
    gender                 = EXCLUDED.gender,
    gender_other           = EXCLUDED.gender_other,
    orientation            = EXCLUDED.orientation,
    orientation_other      = EXCLUDED.orientation_other,
    birth_country          = EXCLUDED.birth_country,
    insurance              = EXCLUDED.insurance,
    doctor                 = EXCLUDED.doctor,
    hiv_test               = EXCLUDED.hiv_test,
    risk_type              = EXCLUDED.risk_type,
    risk_type_other        = EXCLUDED.risk_type_other,
    prep_use               = EXCLUDED.prep_use,
    hiv_risk_selfest       = EXCLUDED.hiv_risk_selfest,
    hiv_test_prev          = EXCLUDED.hiv_test_prev,
    hiv_test_prev_count    = EXCLUDED.hiv_test_prev_count,
    hiv_test_prev_year     = EXCLUDED.hiv_test_prev_year,
    hiv_test_prev_confirm  = EXCLUDED.hiv_test_prev_confirm,
    sexual_risk_time       = EXCLUDED.sexual_risk_time,
    risk_situation         = EXCLUDED.risk_situation,
    risk_situation_other   = EXCLUDED.risk_situation_other,
    risk_country           = EXCLUDED.risk_country,
    risk_gv                = EXCLUDED.risk_gv,
    risk_condom            = EXCLUDED.risk_condom,
    risk_oral              = EXCLUDED.risk_oral,
    risk_reasons           = EXCLUDED.risk_reasons,
    risk_reasons_other     = EXCLUDED.risk_reasons_other,
    risk_drugs             = EXCLUDED.risk_drugs,
    sti_history_yesno      = EXCLUDED.sti_history_yesno,
    sti_history_which      = EXCLUDED.sti_history_which,
    sti_history_which_other= EXCLUDED.sti_history_which_other,
    sti_history_years      = EXCLUDED.sti_history_years,
    hep_a_history          = EXCLUDED.hep_a_history,
    hep_b_history          = EXCLUDED.hep_b_history,
    system_source          = EXCLUDED.system_source,
    system_created_at      = EXCLUDED.system_created_at,
    system_fe_version      = EXCLUDED.system_fe_version,
    system_schema_version  = EXCLUDED.system_schema_version;